//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.Entity.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BkpCustomerOrder
    {
        public System.Guid BkpID { get; set; }
        public System.Guid FileUploadedId { get; set; }
        public string order_number { get; set; }
        public Nullable<int> qty { get; set; }
        public string user_id { get; set; }
        public System.DateTime BkpDate { get; set; }
    }
}
