//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.Entity.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStorageInfo
    {
        public System.Guid FileUploadId { get; set; }
        public string OriginalFileName { get; set; }
        public string StoredFileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
